### ISSUE TITLE
 adding tag tout RssItem

### ISSUE THREAD

**Issue by ayziaa** [ShirwaM/Simplistic-RSS#2]
I've been using your lib ans it work very well. However I'm trying to add a tag for content to get the content of articles but I'm not getting an result with getContent() added. I did what was mentioned in the customization of the readme. Any idea of what I missed? It could come from the feed itself but I have no way of checking that.

**Comment by ShirwaM** [comment]
Hmm. What does the feed look like?

**Comment by ShirwaM** [comment]
I haven't heard back yet, so I am guessing its safe to close this issue. Please let me know if you still need help figuring out stuff. Thanks!
