### ISSUE TITLE
Description syntax conflicts with sax parser

### ISSUE THREAD

**Issue by fenimore** [ShirwaM/Simplistic-RSS#4]
Hi, I'm not quite sure what's going on, but when the feedreader readers the description node of a feed, the string is either entirely or partially missing. I think the & symbols have something to do with it, here is a sample description text:

```
  <description>Headlines for December 08, 2015; &quot;I Want a World of Peace&quot;: In Exclusive Interview UK Labour Head Jeremy Corbyn Opposes Bombing Syria; &quot;A Legal Black Hole&quot;: Jeremy Corbyn Calls for Closing of Guant&#225;namo, Hails Release of Shaker Aamer; Jeremy Corbyn Connects Western Bombing Campaigns &amp; Refugee Crisis: &quot;What Goes Around Comes Around&quot;; War &amp; Climate Change: Jeremy Corbyn on the Brutal Quest for Oil &amp; the Need for a Sustainable Planet; Top Climate Expert: Crisis is Worse Than We Think &amp; Scientists Are Self-Censoring to Downplay Risk; &quot;Loss and Damage&quot;: U.S. Stymies Push for Compensation for Climate Devastation at U.N. Climate Summit; Indian PM Links Worst Floods in a Century to Climate Change as More Cities Face Extreme Weather</description>
```

**Comment by ShirwaM** [comment]
Oh that's odd. I will take a look at it. Thanks for reporting.

**Comment by fenimore** [comment]
https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.democracynow.org%2Fpodcast.xml

I checked with the w3 validator, and I think the problem is from the server, not the library. w3 warns that "Your feed appears to be encoded as "UTF-8", but your server is reporting "US-ASCII""

**Comment by kukosek** [comment]
I fixed this (but a little bit late :-) ) , take a look at my pull request https://github.com/ShirwaM/Simplistic-RSS/pull/9
